trigger:
- main

pool:
  name: pipeline-agent

variables:
  backendServiceArm: pipeline-svc

  backendAzureRmResourceGroupName: pipeline-rg

  backendAzureRmStorageAccountName: pipelinestrg456


  backendAzureRmContainerName: pipeline-container

  backendAzureRmKey: QA.tfstate

stages:
- template: Pipeline/terraform-plan.yaml
- template: Pipeline/terraform-apply.yaml